server:
  port: 8090
spring:
  security:
    user:
      name: config
      password: Cl0vdsec.sansoft
  mvc:
    servlet:
      load-on-startup: 1
  application:
    name: config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://discovery:Cl0vdsec.eureka@localhost:8761/eureka/
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
  hystrix:
    enabled: true #启用熔断机制
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE