server:
  port: 8761
spring:
  security:
    user:
      name: discovery
      password: Cl0vdsec.eureka
  mvc:
    servlet:
      load-on-startup: 1  
  application:
    name: discovery
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
    healthcheck:
      enabled: true
logging:
  config: classpath:log4j2.xml      